#! /bin/bash

exitConfirmation(){
    echo -e "\nWould you like to close the program or not? (y|n): \c"
    read ans
    if [ ${ans,,} == y ]
    then
        echo Exitted at $(date).
        cat thankyou
        exit
    fi
    startapp
 }

getBestMember(){
    PS3='Select the number from the list to display the information of
the member: '
    select member in ${choose[@]}
    do
        if [ -z $member ]
        then
            echo Please Try Again! Choose from the above list only
            getBestMember
	fi
	echo You chose $member as your favourite member.
        if [ -e $member ]
        then
		cat FM
	fi
	cat $member
        exitConfirmation
    done
}

memberErr(){
    echo -e "Members are repeating or there is no such member in the
list\nYou can only choose 3 members\nPlease try Again!"
    validateMember
}

validateMember(){
    echo -e "Enter any 3 members' code from the above list:- \c"
    read m1 m2 m3
    declare -a choose=($m1 $m2 $m3)
    for i in ${choose[@]}
    do
        if [[ $i = JL || $i = AY || $i = FM || $i = DH || $i = KC ]]
        then
		continue 
	fi
	memberErr
    done
    if [[ ${#choose[@]} -eq 3 && $m1 != $m2 && $m1 != $m3 && $m2 != $m3
]]
    then
	getBestMember
    fi
    memberErr
 }

getOptionsMenu(){
    	echo Welcome
	echo Name:		$unam
	echo ID:          	$uid
	echo Login time:  	$(date)

   	 echo '
Top 5 bands
------------------------------- 
| Band name | Band code        | 
------------------------------- 
| Beatles   |     BEA          | 
| AC/DC     |     AD           |
| Queen     |     QUE          | 
| Blondie   |     BLO          | 
| Nirvana   |     NIR          |
 ------------------------------

Choose one band code from the above list
    '
    until [ "$band" == AD ]
    do
        echo -e "your guess for best band: \c"
        read band
        if [ $band != AD ]
        then
            echo This is not the right band. Please Try Again.
        fi
    done
    echo -e "Congratulations! you chose AC/DC\n"
    cat AD
    band=''
    echo '
Top 5 members
-------------------------------------- 
|     Member Name   |   Member Code   |
 -------------------------------------
| John Lennon       |   JL            | 
| Angus Young       |   AY            | 
| Freddie Mercury   |   FM            | 
| Debbie Harry      |   DH            | 
| Kurt Cobian       |   KC            |
--------------------------------------
'
}

startapp(){
    getOptionsMenu

    validateMember
}

counter=0
while [ $counter -lt 3 ]
do
    echo -e "Enter secret key: \c"
    read -s key
    if [ $key == Karmaraj ]
    then
        if [ $# -ne 2 ]
        then
            echo -e 'Exactly 2 arguments required to run the program.
\nFirst: your name. \nSecond: your ID.'
break
        fi
        if [[ $1 =~ [0-9] || $2 =~ [aA-zZ] ]]
        then
            echo Invalid input. The first input must be your name and
The second input must be your ID.
break
fi
        uname=$1
        uid=$2
startapp
break
fi
    echo You have $(( 2-$counter )) tries remaining
    (( counter++ ))
done

echo Exitted at $(date).
